version: '3.8'

services:
  scanchain:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    restart: unless-stopped